/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        /**
         * Flashcard Methods.
         */
        //Create a new flashcard
        Flashcard fc1 = new Flashcard("Hi in Swedish?", "Hej");

        // Get card question and answer as separate String
        System.out.println("Question: " + fc1.getQuestion()); // print question
        System.out.println("Answer: " + fc1.getAnswer()); // print answer

        // Get card and question as toString()
        Flashcard fcToString = new Flashcard("What did you eat for breakfast in Swedish?", "Vad åt du till frukost?");
        String result = fcToString.toString();
        System.out.println(result);

        //Create a FlashcardDeck, and add 2 cards to it
        FlashcardDeck fcDeck = new FlashcardDeck();

        Flashcard fc2 = new Flashcard("Thanks in Swedish?", "Tack");
        Flashcard fc3 = new Flashcard("What time did you get up this morning in Swedish?", "Vilken tid gick du upp imorse?");
        fcDeck.addFlashcard(fc1);
        fcDeck.addFlashcard(fc2);
        fcDeck.addFlashcard(fc3);

        System.out.println("\nFirst flashcard: " + fcDeck.getNextFlashcard()); // shows the 1st card
        System.out.println("Next flashcard: " + fcDeck.getNextFlashcard()); // shows the 2st card

        System.out.println("\nBefore shuffle 3 cards: " + fcDeck.toString());
        //Shuffle deck
        fcDeck.shuffleCards();
        System.out.println("\nAfter shuffle 3 cards: " + fcDeck.toString());

        //Creat a new user passing name and socre
        User user = new User("Tom", 1);
        System.out.println("\nName: " + user.getUserName() + "\nScore: " + user.getScore());

        //Create a QuizService and pass flashcardDeck
        //Create card and add to FlashcardDeck
        Flashcard fcWithoutService = new Flashcard("\nHow are you in Swedish?", "Hur mår du?");
        FlashcardDeck fcDeckService = new FlashcardDeck();

        fcDeckService.addFlashcard(fcWithoutService);

        //Call QuizService to inject the deck
        QuizService service = new QuizService();
        service.setFlashcardDeck(fcDeckService);

        Flashcard fcThroughService = service.getReturnedFlashcard(); // ask the service for a card

        // Check if question from returnedCard equals the original fcNew question
        System.out.println("\nGet the card without service: " + fcWithoutService.getQuestion());
        System.out.println("Get the card through service: " + fcThroughService.getQuestion());
    }
}
