/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

/* Test card, deck, user content not null.
 */
class AppTest {

    /**
     * Test flashcard related methods return not null.
     */
    @Test
    void testCardHasQuestion() {
        Flashcard fc = new Flashcard("Hi in Swedish?", "Hej");
        assertNotNull(fc.getQuestion());
    }

    @Test
    void tesCardHasAnswer() {
        Flashcard fc = new Flashcard("Bye in Swedish?", "Hej då");
        assertNotNull(fc.getAnswer());
    }

    @Test
    void testCardHasQuestionAndAnswer() {
        Flashcard fc = new Flashcard("What did you eat for breakfast in Swedish?", "Vad åt du till frukost?");
        String result = fc.toString();
        assertNotNull(result);
    }

    @Test
    void testDeckHasNextCard() {
        Flashcard fc1 = new Flashcard("Hi in Swedish?", "Hej");
        Flashcard fc2 = new Flashcard("Thanks in Swedish?", "Tack");

        FlashcardDeck fcDeck = new FlashcardDeck();
        fcDeck.addFlashcard(fc1);
        fcDeck.addFlashcard(fc2);

        assertNotNull(fcDeck.getNextFlashcard());
        assertNotNull(fcDeck.getNextFlashcard());
    }

    @Test
    void testUserHasName() {
        User user = new User("Lily", 0);
        assertNotNull(user.getUserName());
    }

    @Test
    void testUserShouldHaveScore() {
        User user = new User("Bob", 20);
        assertNotNull(user.getScore());
    }

}
