/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void cardHasQuestion() {
        Flashcard fc = new Flashcard("Hi in Swedish?", "Hej");
        assertNotNull(fc.getQuestion());
    }

    @Test void deckHasNextCard() {
        Flashcard fc1 = new Flashcard("Hi in Swedish?", "Hej");
        Flashcard fc2 = new Flashcard("Thanks in Swedish?", "Tack");

        FlashcardDeck fcDeck = new FlashcardDeck(); 
        fcDeck.addFlashcard(fc1);
        fcDeck.addFlashcard(fc2);

        assertNotNull(fcDeck.getNextFlashcard());
        assertNotNull(fcDeck.getNextFlashcard());
    }
}
