/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void cardHasQuestion() {
        Flashcard fc = new Flashcard("Hi in Swedish?", "Hej");
        assertNotNull(fc.getQuestion(), "Hi in Swedish?");
    }
}
