/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// import Flashcard;

public class App {

    public static void main(String[] args) {
        //Create new flashcasd
        Flashcard fc = new Flashcard("How to say hi in Swedish?", "Hej");
        System.out.println("Question: " + fc.getQuestion());

    }
}
